version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.3
    steps:
      - checkout
      - run:
          name: Zip files
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            sudo apt-get update -y
            sudo apt-get install -y less
            ls -al
            zip -r myproject.zip handler.py
            echo "Zip Done"
            sudo chmod 775 myproject.zip
            ls -al
      - run:
          name: Code Deployment
          command: |
            ls -al
            pwd
            aws lambda update-function-code --function-name lambda_function_name --zip-file fileb:///home/circleci/project/myproject.zip
























# version: 2.1
# orbs:
#   aws-s3: circleci/aws-s3@1.0.15
#   aws-code-deploy: circleci/aws-code-deploy@1.0.1
# jobs:
#   build:
#     docker:
#       - image: circleci/python:3.8.3
#     steps:
#       - checkout
#       - run:
#           name: Zipping Files
#           command: |
#             pwd
#             ls -al
#             zip -r myproject.zip myproject/
#             echo "Zip Done"
#             sudo chmod 775 myproject.zip
#             ls -al
#       - aws-s3/copy:
#           from: myproject.zip
#           to: s3://codedeploy.abhithakkar.me
# workflows:
#   deploy_application:
#     jobs:
#       - build
#       - aws-code-deploy/deploy:
#           application-name: csye6225-webapp
#           bundle-bucket: codedeploy.abhithakkar.me
#           bundle-key: myproject
#           deployment-group: csye6225-webapp-deployment
#           service-role-arn: arn:aws:iam::682607698449 :roleCodeDeployServiceRole



